basePath: /
definitions:
  api.AddBookRequest:
    properties:
      authors:
        example:
        - J.R.R. Tolkien
        items:
          type: string
        type: array
      book_images:
        $ref: '#/definitions/store.BookImages'
      chapters:
        items:
          $ref: '#/definitions/store.Chapter'
        type: array
      description:
        example: A fantasy novel...
        type: string
      isbn_10:
        example: "0261102214"
        type: string
      isbn_13:
        example: "9780261102217"
        type: string
      page_count:
        example: 310
        type: integer
      published_date:
        example: "1937-09-21"
        type: string
      publisher:
        example: George Allen & Unwin
        type: string
      title:
        example: The Hobbit
        type: string
    type: object
  api.AddChapterCommentRequest:
    properties:
      body:
        example: I loved this chapter
        type: string
    type: object
  api.HTTPError:
    properties:
      error:
        type: string
    type: object
  api.PaginatedBooksResponse:
    properties:
      books:
        items:
          $ref: '#/definitions/store.Book'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  api.PaginatedCommentsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/store.ChapterComment'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  api.RegisterUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  api.UserBooksResponse:
    properties:
      limit:
        type: integer
      page:
        type: integer
      user_books:
        items:
          $ref: '#/definitions/store.BasicUserBook'
        type: array
    type: object
  api.createTokenRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  store.BasicUserBook:
    properties:
      book:
        $ref: '#/definitions/store.Book'
      id:
        type: integer
      status:
        type: string
      user_id:
        type: integer
    type: object
  store.Book:
    properties:
      authors:
        items:
          type: string
        type: array
      book_images:
        $ref: '#/definitions/store.BookImages'
      chapters:
        items:
          $ref: '#/definitions/store.Chapter'
        type: array
      description:
        type: string
      id:
        type: integer
      isbn_10:
        type: string
      isbn_13:
        type: string
      page_count:
        type: integer
      published_date:
        type: string
      publisher:
        type: string
      title:
        type: string
    type: object
  store.BookImages:
    properties:
      large_url:
        type: string
      medium_url:
        type: string
      small_url:
        type: string
      thumbnail_url:
        type: string
    type: object
  store.Chapter:
    properties:
      id:
        type: integer
      number:
        type: integer
      title:
        type: string
    type: object
  store.ChapterComment:
    properties:
      body:
        type: string
      chapter_id:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      user:
        $ref: '#/definitions/store.User'
      user_id:
        type: integer
    type: object
  store.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      role:
        $ref: '#/definitions/store.UserRole'
      username:
        type: string
    type: object
  store.UserRole:
    enum:
    - user
    - admin
    type: string
    x-enum-varnames:
    - RoleUser
    - RoleAdmin
  tokens.Token:
    properties:
      expriy:
        type: string
      token:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:5000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: The BookClubApp to manage, share, and comment your favorite books.
    The goal is to create a space where you can interact and express your ideas and
    though as you go through the chapters of the books you are reading.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BookClubApp
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Retrieves all books with pagination.
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 20
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.PaginatedBooksResponse'
        "400":
          description: 'Error: Invalid or missing id'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "404":
          description: 'Error: Book not found'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      summary: Get all books
      tags:
      - books
    post:
      consumes:
      - application/json
      description: Registers a book in the system.
      parameters:
      - description: Add book request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.AddBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Book'
        "401":
          description: 'Error: Unauthorized'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "409":
          description: 'Error: Duplicate record'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      security:
      - BearerAuth: []
      summary: Add a book
      tags:
      - books
  /books/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves the details of a book by their id.
      parameters:
      - description: The id of the book
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Book'
        "404":
          description: 'Error: Book not found'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      summary: Get a book by id
      tags:
      - books
    put:
      consumes:
      - application/json
      description: Updates a book's information in the system.
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      - description: Add book request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.AddBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Book'
        "401":
          description: 'Error: Unauthorized'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "404":
          description: 'Error: User not found'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      security:
      - BearerAuth: []
      summary: Update a book
      tags:
      - books
  /chapters/{chapter_id}/comments:
    get:
      consumes:
      - application/json
      description: Retrieves the comments of a specific chapter.
      parameters:
      - description: Chapter ID
        in: path
        name: chapter_id
        required: true
        type: integer
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 20
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.PaginatedCommentsResponse'
        "400":
          description: 'Error: Invalid or missing id'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "404":
          description: 'Error: Comment not found'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      summary: Get the comments of a book's chapter
      tags:
      - comments
    post:
      consumes:
      - application/json
      description: Adds a user comment on a book's chapter. Expects a JSON body containing
        the body of the comment. Returns the created comment object on success.
      parameters:
      - description: Chapter ID
        in: path
        name: chapter_id
        required: true
        type: integer
      - description: Register comment request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.AddChapterCommentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.ChapterComment'
        "400":
          description: 'Error: Invalid Request'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "401":
          description: 'Error: Unauthorized'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      security:
      - BearerAuth: []
      summary: Add a comment to a book's chapter
      tags:
      - comments
  /chapters/{chapter_id}/comments/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a book's chapter comment. Returns the deleted comment on
        success.
      parameters:
      - description: Chapter ID
        in: path
        name: chapter_id
        required: true
        type: integer
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: 'Error: Unauthorized'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "404":
          description: 'Error: Comment not found'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      security:
      - BearerAuth: []
      summary: Delete a comment to a book's chapter by id
      tags:
      - comments
    get:
      consumes:
      - application/json
      description: Retrieves the details of a specific comment .
      parameters:
      - description: Chapter ID
        in: path
        name: chapter_id
        required: true
        type: integer
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.ChapterComment'
        "400":
          description: 'Error: Invalid or missing id'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "404":
          description: 'Error: Comment not found'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      summary: Get a comment to a book's chapter by id
      tags:
      - comments
    put:
      consumes:
      - application/json
      description: Updates a book's chapter comment. Expects a body with the edited
        comment. Returns the updated comment on success.
      parameters:
      - description: Chapter ID
        in: path
        name: chapter_id
        required: true
        type: integer
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      - description: Edit comment request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.AddChapterCommentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.ChapterComment'
        "401":
          description: 'Error: Unauthorized'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "404":
          description: 'Error: Comment not found'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      security:
      - BearerAuth: []
      summary: Update a comment to a book's chapter
      tags:
      - comments
  /tokens/authentication:
    post:
      consumes:
      - application/json
      description: Authenticates a user in the system. Expects a JSON body containing
        username and password. Returns a bearer token on success.
      parameters:
      - description: Authentication Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.createTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tokens.Token'
        "401":
          description: 'Error: Invalid Credentials'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      summary: Login
      tags:
      - auth
  /users:
    get:
      consumes:
      - application/json
      description: Retrieves the details of a user by their username.
      parameters:
      - description: Username
        example: johndoe
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.User'
        "400":
          description: 'Error: Invalid or missing username'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "404":
          description: 'Error: User not found'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      summary: Get a user by username
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Registers a new user in the system. Expects a JSON body containing
        username, email, and password. Returns the created account object on success.
      parameters:
      - description: Register user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.User'
        "400":
          description: 'Error: Invalid Request'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "409":
          description: 'Error: Email or Username already exists'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      summary: Register a new user account
      tags:
      - users
  /users/{user_id}/books:
    get:
      consumes:
      - application/json
      description: Retrieves the books for a given user. Optional `status` query parameter
        filters by reading status.
      parameters:
      - description: Filter by status (wishlist|reading|completed)
        in: query
        name: status
        type: string
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 20
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UserBooksResponse'
        "400":
          description: 'Error: Invalid or missing id'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      security:
      - BearerAuth: []
      summary: Get a user's books
      tags:
      - user_books
    post:
      consumes:
      - application/json
      description: Adds a book to a user's collection with a specified status.
      parameters:
      - description: Book ID
        in: query
        name: book_id
        required: true
        type: integer
      - description: Filter by status (wishlist|reading|completed)
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UserBooksResponse'
        "400":
          description: 'Error: Invalid or missing id'
          schema:
            $ref: '#/definitions/api.HTTPError'
        "500":
          description: 'Error: Internal server error'
          schema:
            $ref: '#/definitions/api.HTTPError'
      security:
      - BearerAuth: []
      summary: Add a book to a user's collection
      tags:
      - user_books
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and your token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
